<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HomepageDestination;
use Illuminate\Support\Str;

class HomepageDestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $destinations = [
            // National Parks
            [
                'name' => 'Serengeti National Park',
                'slug' => 'serengeti-national-park',
                'short_description' => 'Witness the Great Migration and the Big Five in Africa\'s most iconic wildlife sanctuary.',
                'full_description' => 'Serengeti National Park is one of Africa\'s most famous national parks and a UNESCO World Heritage Site. Spanning 14,750 square kilometers, it\'s home to the annual Great Migration where over 1.5 million wildebeest and 250,000 zebras migrate in search of fresh grazing. The park offers incredible wildlife viewing opportunities year-round, with the Big Five (lion, leopard, elephant, buffalo, and rhino) all present. The endless plains, acacia-dotted savannas, and diverse ecosystems make it a photographer\'s paradise.',
                'featured_image_url' => 'images/destinations/serengeti.jpg',
                'image_gallery' => [
                    'images/destinations/serengeti-1.jpg',
                    'images/destinations/serengeti-2.jpg',
                    'images/destinations/serengeti-3.jpg',
                    'images/destinations/serengeti-4.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Northern Tanzania',
                'city' => 'Serengeti',
                'category' => 'National Parks',
                'price' => 450,
                'price_display' => 'Starting from $450 per person',
                'duration' => '3-7 days',
                'rating' => 4.9,
                'is_active' => true,
                'is_featured' => true,
                'meta_title' => 'Serengeti National Park - Great Migration Safari | Lau Paradise Adventures',
                'meta_description' => 'Experience the Great Migration in Serengeti National Park. Witness the Big Five and incredible wildlife in Africa\'s most iconic safari destination.',
                'meta_keywords' => 'Serengeti, Great Migration, Big Five, wildlife safari, Tanzania national park',
                'og_image_url' => 'images/Serengetei-NP-2.jpeg',
                'display_order' => 1,
            ],
            [
                'name' => 'Ngorongoro Crater',
                'slug' => 'ngorongoro-crater',
                'short_description' => 'Descend into the world\'s largest intact caldera, a natural wonder teeming with wildlife.',
                'full_description' => 'The Ngorongoro Crater is the world\'s largest inactive, intact, and unfilled volcanic caldera. Formed 2-3 million years ago, this natural wonder spans 260 square kilometers and is home to over 25,000 large animals. The crater floor offers some of the best wildlife viewing in Africa, with high concentrations of lions, elephants, buffalo, and the rare black rhino. The unique ecosystem, combined with the stunning scenery of the crater walls, makes it one of Africa\'s Seven Natural Wonders.',
                'featured_image_url' => 'images/safari_home-1.jpg',
                'image_gallery' => [
                    'images/DSC05518-1536x1024.jpg',
                    'images/Serengetei-NP-2.jpeg',
                    'images/hero-slider/animal-movement.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Northern Tanzania',
                'city' => 'Ngorongoro',
                'category' => 'National Parks',
                'price' => 380,
                'price_display' => 'Starting from $380 per person',
                'duration' => '1-2 days',
                'rating' => 4.8,
                'is_active' => true,
                'is_featured' => true,
                'meta_title' => 'Ngorongoro Crater - World\'s Largest Caldera | Lau Paradise Adventures',
                'meta_description' => 'Explore Ngorongoro Crater, one of Africa\'s Natural Wonders. Witness incredible wildlife density in this unique volcanic caldera.',
                'meta_keywords' => 'Ngorongoro Crater, caldera, Big Five, Tanzania, wildlife viewing',
                'og_image_url' => 'images/safari_home-1.jpg',
                'display_order' => 2,
            ],
            [
                'name' => 'Tarangire National Park',
                'slug' => 'tarangire-national-park',
                'short_description' => 'Home to massive elephant herds and ancient baobab trees in Tanzania\'s elephant paradise.',
                'full_description' => 'Tarangire National Park is famous for its large elephant herds, with over 3,000 elephants during the dry season. The park features stunning baobab trees, some over 1,000 years old, creating a unique and photogenic landscape. Tarangire offers excellent wildlife viewing, especially during the dry season (June-October) when animals congregate around the Tarangire River. The park is also a birdwatcher\'s paradise with over 550 bird species recorded.',
                'featured_image_url' => 'images/Tarangire-NP-1.jpeg',
                'image_gallery' => [
                    'images/Angata-Tarangire-2-1-1536x863.jpeg',
                    'images/safari_home-1.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Northern Tanzania',
                'city' => 'Tarangire',
                'category' => 'National Parks',
                'price' => 320,
                'price_display' => 'Starting from $320 per person',
                'duration' => '1-2 days',
                'rating' => 4.7,
                'is_active' => true,
                'is_featured' => true,
                'meta_title' => 'Tarangire National Park - Elephant Paradise | Lau Paradise Adventures',
                'meta_description' => 'Visit Tarangire National Park to see massive elephant herds and ancient baobab trees. Excellent wildlife viewing in northern Tanzania.',
                'meta_keywords' => 'Tarangire, elephants, baobab trees, Tanzania safari',
                'og_image_url' => 'images/Tarangire-NP-1.jpeg',
                'display_order' => 3,
            ],
            [
                'name' => 'Lake Manyara National Park',
                'slug' => 'lake-manyara-national-park',
                'short_description' => 'A birdwatcher\'s paradise with tree-climbing lions and diverse ecosystems in a compact park.',
                'full_description' => 'Lake Manyara National Park is a compact but diverse park known for its tree-climbing lions, large flocks of flamingos, and diverse birdlife. The park features a shallow alkaline lake, groundwater forests, and open grasslands. Despite its small size (330 square kilometers), it offers excellent wildlife viewing and is particularly famous for its bird watching opportunities with over 400 species. The park\'s unique feature is the lions that climb trees, a behavior rarely seen elsewhere.',
                'featured_image_url' => 'images/destinations/lake-manyara.jpg',
                'image_gallery' => [
                    'images/destinations/lake-manyara-1.jpg',
                    'images/destinations/lake-manyara-2.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Northern Tanzania',
                'city' => 'Lake Manyara',
                'category' => 'National Parks',
                'price' => 280,
                'price_display' => 'Starting from $280 per person',
                'duration' => '1 day',
                'rating' => 4.6,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Lake Manyara National Park - Bird Watching Paradise | Lau Paradise Adventures',
                'meta_description' => 'Explore Lake Manyara National Park. See tree-climbing lions, flamingos, and over 400 bird species in this diverse ecosystem.',
                'meta_keywords' => 'Lake Manyara, tree-climbing lions, bird watching, flamingos, Tanzania',
                'og_image_url' => 'images/hero-slider/animal-movement.jpg',
                'display_order' => 4,
            ],
            [
                'name' => 'Arusha National Park',
                'slug' => 'arusha-national-park',
                'short_description' => 'A diverse park near Arusha featuring Mount Meru, diverse wildlife, and beautiful landscapes.',
                'full_description' => 'Arusha National Park is located just 25 kilometers from Arusha town, making it easily accessible. The park features Mount Meru (Tanzania\'s second-highest peak), the Momela Lakes, and diverse ecosystems from montane forest to alpine moorland. It\'s perfect for day trips and offers excellent bird watching, colobus monkeys, and beautiful scenery. The park is less crowded than other northern circuit parks, offering a more intimate safari experience.',
                'featured_image_url' => 'images/arusha.jpeg',
                'image_gallery' => [
                    'images/safari_home-1.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Northern Tanzania',
                'city' => 'Arusha',
                'category' => 'National Parks',
                'price' => 250,
                'price_display' => 'Starting from $250 per person',
                'duration' => '1 day',
                'rating' => 4.5,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Arusha National Park - Mount Meru & Wildlife | Lau Paradise Adventures',
                'meta_description' => 'Visit Arusha National Park near Arusha town. See Mount Meru, diverse wildlife, and beautiful landscapes in this accessible park.',
                'meta_keywords' => 'Arusha National Park, Mount Meru, day trip, Tanzania',
                'og_image_url' => 'images/arusha.jpeg',
                'display_order' => 5,
            ],
            // Mountain Trekking
            [
                'name' => 'Mount Kilimanjaro',
                'slug' => 'mount-kilimanjaro',
                'short_description' => 'Conquer Africa\'s highest peak at 5,895 meters. Multiple routes available for all experience levels.',
                'full_description' => 'Mount Kilimanjaro is Africa\'s highest mountain and the world\'s tallest free-standing mountain at 5,895 meters (19,341 feet). It\'s one of the Seven Summits and offers several climbing routes including Marangu, Machame, Lemosho, Rongai, and more. The mountain features five distinct climate zones from tropical rainforest to arctic summit. Climbing Kilimanjaro doesn\'t require technical mountaineering skills, but it does require excellent physical fitness and proper acclimatization. The summit offers breathtaking views and a sense of incredible achievement.',
                'featured_image_url' => 'images/destinations/kilimanjaro.jpg',
                'image_gallery' => [
                    'images/destinations/kilimanjaro-1.jpg',
                    'images/destinations/kilimanjaro-2.jpg',
                    'images/destinations/kilimanjaro-3.jpg',
                    'images/destinations/kilimanjaro-4.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Northern Tanzania',
                'city' => 'Moshi',
                'category' => 'Mountain Trekking',
                'price' => 1776,
                'price_display' => 'Starting from $1,776 per person',
                'duration' => '6-9 days',
                'rating' => 4.8,
                'is_active' => true,
                'is_featured' => true,
                'meta_title' => 'Mount Kilimanjaro Climbing - Africa\'s Highest Peak | Lau Paradise Adventures',
                'meta_description' => 'Climb Mount Kilimanjaro, Africa\'s highest peak. Multiple routes available with professional guides. Summit Uhuru Peak at 5,895m.',
                'meta_keywords' => 'Kilimanjaro, mountain climbing, Uhuru Peak, Tanzania, Africa highest peak',
                'og_image_url' => 'images/hero-slider/kilimanjaro-climbing.jpg',
                'display_order' => 6,
            ],
            [
                'name' => 'Mount Meru',
                'slug' => 'mount-meru',
                'short_description' => 'Tanzania\'s second-highest peak, perfect for acclimatization before Kilimanjaro or as a standalone climb.',
                'full_description' => 'Mount Meru stands at 4,566 meters (14,980 feet) and is Tanzania\'s second-highest peak. Located in Arusha National Park, it offers a challenging but rewarding climb with stunning views of Kilimanjaro on clear days. The climb typically takes 3-4 days and is often used as acclimatization training before attempting Kilimanjaro. The route passes through diverse ecosystems including montane forest, heath, and alpine desert. The summit offers panoramic views of the surrounding landscape.',
                'featured_image_url' => 'images/hero-slider/kilimanjaro-climbing.jpg',
                'image_gallery' => [
                    'images/arusha.jpeg',
                    'images/safari_home-1.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Northern Tanzania',
                'city' => 'Arusha',
                'category' => 'Mountain Trekking',
                'price' => 850,
                'price_display' => 'Starting from $850 per person',
                'duration' => '3-4 days',
                'rating' => 4.7,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Mount Meru Climbing - Tanzania\'s Second Highest Peak | Lau Paradise Adventures',
                'meta_description' => 'Climb Mount Meru, Tanzania\'s second-highest peak. Perfect for acclimatization or as a standalone adventure in Arusha National Park.',
                'meta_keywords' => 'Mount Meru, mountain climbing, Arusha National Park, Tanzania',
                'og_image_url' => 'images/hero-slider/kilimanjaro-climbing.jpg',
                'display_order' => 7,
            ],
            // Beaches
            [
                'name' => 'Zanzibar',
                'slug' => 'zanzibar',
                'short_description' => 'Tropical paradise with pristine beaches, rich culture, and the historic Stone Town UNESCO World Heritage Site.',
                'full_description' => 'Zanzibar is a tropical archipelago off the coast of Tanzania, famous for its pristine white sand beaches, crystal-clear turquoise waters, and rich Swahili culture. Stone Town, the historic heart of Zanzibar City, is a UNESCO World Heritage Site with narrow alleys, historic buildings, and vibrant markets. The island offers world-class diving, snorkeling, spice tours, and cultural experiences. From luxury beach resorts to authentic local experiences, Zanzibar provides the perfect beach holiday complement to a Tanzania safari.',
                'featured_image_url' => 'images/zanzibar_home.jpg',
                'image_gallery' => [
                    'images/hero-slider/zanzibar-beach.jpg',
                    'images/11-Days-Safari-trip-Tanzania-Zanzibar-1536x1024.jpg',
                    'images/13-Days-Safari-Zanzibar-holiday-1518x1536.jpg',
                    'images/hero-slider/morning.jpg',
                    'images/safari_home-1.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Zanzibar',
                'city' => 'Stone Town',
                'category' => 'Beaches',
                'price' => 605,
                'price_display' => 'Starting from $605 per person',
                'duration' => '3-10 days',
                'rating' => 4.9,
                'is_active' => true,
                'is_featured' => true,
                'meta_title' => 'Zanzibar Beach Holiday - Tropical Paradise | Lau Paradise Adventures',
                'meta_description' => 'Experience Zanzibar\'s pristine beaches, Stone Town UNESCO site, and rich Swahili culture. Perfect beach holiday destination.',
                'meta_keywords' => 'Zanzibar, beach holiday, Stone Town, tropical paradise, Tanzania',
                'og_image_url' => 'images/zanzibar_home.jpg',
                'display_order' => 8,
            ],
            [
                'name' => 'Pemba Island',
                'slug' => 'pemba-island',
                'short_description' => 'The "Green Island" - pristine and less developed, perfect for diving and authentic experiences.',
                'full_description' => 'Pemba Island is Zanzibar\'s northern neighbor, known as the "Green Island" due to its lush vegetation. Less developed than Zanzibar, Pemba offers a more authentic and secluded experience. The island is famous for world-class diving, with pristine coral reefs and excellent visibility. It\'s also known for traditional dhow building and spice cultivation. Perfect for travelers seeking tranquility and authentic cultural experiences away from the crowds.',
                'featured_image_url' => 'images/zanzibar_home.jpg',
                'image_gallery' => [
                    'images/hero-slider/zanzibar-beach.jpg',
                    'images/hero-slider/morning.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Zanzibar',
                'city' => 'Pemba',
                'category' => 'Beaches',
                'price' => 750,
                'price_display' => 'Starting from $750 per person',
                'duration' => '4-7 days',
                'rating' => 4.6,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Pemba Island - Diving & Authentic Experience | Lau Paradise Adventures',
                'meta_description' => 'Discover Pemba Island, the Green Island. World-class diving, pristine beaches, and authentic cultural experiences.',
                'meta_keywords' => 'Pemba Island, diving, Zanzibar, Tanzania',
                'og_image_url' => 'images/zanzibar_home.jpg',
                'display_order' => 9,
            ],
            // Southern Circuit
            [
                'name' => 'Selous Game Reserve',
                'slug' => 'selous-game-reserve',
                'short_description' => 'Africa\'s largest game reserve offering boat safaris, walking safaris, and authentic wilderness experiences.',
                'full_description' => 'Selous Game Reserve is Africa\'s largest game reserve, covering 50,000 square kilometers. It\'s a UNESCO World Heritage Site and offers a more authentic, less-crowded safari experience compared to the northern circuit. The reserve is famous for its large elephant populations, wild dogs, and diverse birdlife. Unique activities include boat safaris on the Rufiji River and walking safaris with armed rangers. The reserve offers a true wilderness experience away from the tourist crowds.',
                'featured_image_url' => 'images/safari_home-1.jpg',
                'image_gallery' => [
                    'images/Serengetei-NP-2.jpeg',
                    'images/Tarangire-NP-1.jpeg',
                    'images/hero-slider/safari-adventure.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Southern Tanzania',
                'city' => 'Selous',
                'category' => 'Game Reserves',
                'price' => 450,
                'price_display' => 'Starting from $450 per person',
                'duration' => '3-5 days',
                'rating' => 4.7,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Selous Game Reserve - Africa\'s Largest Reserve | Lau Paradise Adventures',
                'meta_description' => 'Explore Selous Game Reserve, Africa\'s largest. Boat safaris, walking safaris, and authentic wilderness experiences.',
                'meta_keywords' => 'Selous, game reserve, boat safari, walking safari, Tanzania',
                'og_image_url' => 'images/safari_home-1.jpg',
                'display_order' => 10,
            ],
            [
                'name' => 'Ruaha National Park',
                'slug' => 'ruaha-national-park',
                'short_description' => 'Tanzania\'s largest national park, known for large elephant herds and excellent predator viewing.',
                'full_description' => 'Ruaha National Park is Tanzania\'s largest national park, covering 20,226 square kilometers. It\'s known for its large elephant herds, with one of the highest concentrations in East Africa. The park offers excellent predator viewing, including lions, leopards, cheetahs, and wild dogs. The Great Ruaha River provides a lifeline for wildlife, especially during the dry season. The park is less visited than northern circuit parks, offering a more exclusive and authentic safari experience.',
                'featured_image_url' => 'images/hero-slider/safari-adventure.jpg',
                'image_gallery' => [
                    'images/Serengetei-NP-2.jpeg',
                    'images/Tarangire-NP-1.jpeg'
                ],
                'country' => 'Tanzania',
                'region' => 'Southern Tanzania',
                'city' => 'Ruaha',
                'category' => 'National Parks',
                'price' => 420,
                'price_display' => 'Starting from $420 per person',
                'duration' => '3-4 days',
                'rating' => 4.6,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Ruaha National Park - Elephant Paradise | Lau Paradise Adventures',
                'meta_description' => 'Visit Ruaha National Park, Tanzania\'s largest. See massive elephant herds and excellent predator viewing in southern Tanzania.',
                'meta_keywords' => 'Ruaha, national park, elephants, Tanzania',
                'og_image_url' => 'images/safari_home-1.jpg',
                'display_order' => 11,
            ],
            [
                'name' => 'Mikumi National Park',
                'slug' => 'mikumi-national-park',
                'short_description' => 'Easily accessible park near Dar es Salaam, perfect for a weekend safari getaway.',
                'full_description' => 'Mikumi National Park is located approximately 300 kilometers from Dar es Salaam, making it easily accessible for a weekend safari. The park features the Mkata Floodplain, which resembles the Serengeti and offers excellent wildlife viewing. Mikumi is home to elephants, lions, giraffes, zebras, and various antelope species. The park is less crowded than northern circuit parks and offers good value for money. Perfect for travelers with limited time or those starting their safari from Dar es Salaam.',
                'featured_image_url' => 'images/safari_home-1.jpg',
                'image_gallery' => [
                    'images/safari_home-1.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Southern Tanzania',
                'city' => 'Mikumi',
                'category' => 'National Parks',
                'price' => 350,
                'price_display' => 'Starting from $350 per person',
                'duration' => '2-3 days',
                'rating' => 4.5,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Mikumi National Park - Weekend Safari | Lau Paradise Adventures',
                'meta_description' => 'Visit Mikumi National Park near Dar es Salaam. Perfect for a weekend safari with excellent wildlife viewing.',
                'meta_keywords' => 'Mikumi, national park, weekend safari, Tanzania',
                'og_image_url' => 'images/safari_home-1.jpg',
                'display_order' => 12,
            ],
            // Cultural & Historical
            [
                'name' => 'Stone Town',
                'slug' => 'stone-town',
                'short_description' => 'UNESCO World Heritage Site with rich Swahili culture, historic architecture, and vibrant markets.',
                'full_description' => 'Stone Town is the historic heart of Zanzibar City and a UNESCO World Heritage Site. The town features narrow winding alleys, historic buildings with ornate carved doors, and a rich blend of Swahili, Arab, Persian, Indian, and European influences. Key attractions include the House of Wonders, Old Fort, Forodhani Gardens, and the vibrant Darajani Market. Stone Town offers excellent opportunities for cultural immersion, shopping for spices and crafts, and experiencing authentic Swahili cuisine.',
                'featured_image_url' => 'images/zanzibar_home.jpg',
                'image_gallery' => [
                    'images/hero-slider/zanzibar-beach.jpg',
                    'images/11-Days-Safari-trip-Tanzania-Zanzibar-1536x1024.jpg',
                    'images/hero-slider/morning.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Zanzibar',
                'city' => 'Stone Town',
                'category' => 'Cultural & Historical',
                'price' => 150,
                'price_display' => 'Starting from $150 per person',
                'duration' => '1-2 days',
                'rating' => 4.8,
                'is_active' => true,
                'is_featured' => true,
                'meta_title' => 'Stone Town Zanzibar - UNESCO World Heritage Site | Lau Paradise Adventures',
                'meta_description' => 'Explore Stone Town, Zanzibar\'s historic heart and UNESCO World Heritage Site. Rich Swahili culture and stunning architecture.',
                'meta_keywords' => 'Stone Town, Zanzibar, UNESCO, Swahili culture, historic',
                'og_image_url' => 'images/zanzibar_home.jpg',
                'display_order' => 13,
            ],
            [
                'name' => 'Arusha',
                'slug' => 'arusha',
                'short_description' => 'Gateway to Tanzania\'s northern safari circuit, a vibrant city with excellent infrastructure.',
                'full_description' => 'Arusha is the gateway city to Tanzania\'s northern safari circuit and is located at the base of Mount Meru. The city serves as the starting point for most safaris to Serengeti, Ngorongoro, Tarangire, and Lake Manyara. Arusha offers good accommodation options, restaurants, and shopping. Key attractions include the Arusha Declaration Museum, Cultural Heritage Centre, and local markets. The city has excellent infrastructure and is well-connected to Kilimanjaro International Airport.',
                'featured_image_url' => 'images/arusha.jpeg',
                'image_gallery' => [
                    'images/safari_home-1.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Northern Tanzania',
                'city' => 'Arusha',
                'category' => 'Cities',
                'price' => 100,
                'price_display' => 'Starting from $100 per person',
                'duration' => '1-2 days',
                'rating' => 4.3,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Arusha - Gateway to Northern Safari Circuit | Lau Paradise Adventures',
                'meta_description' => 'Arusha, the gateway to Tanzania\'s northern safari circuit. Starting point for Serengeti, Ngorongoro, and other northern parks.',
                'meta_keywords' => 'Arusha, Tanzania, safari gateway, northern circuit',
                'og_image_url' => 'images/arusha.jpeg',
                'display_order' => 14,
            ],
            [
                'name' => 'Moshi',
                'slug' => 'moshi',
                'short_description' => 'Base town for Kilimanjaro climbs, offering mountain views and excellent climbing infrastructure.',
                'full_description' => 'Moshi is the base town for Mount Kilimanjaro climbs, located at the foot of Africa\'s highest peak. The town offers excellent views of Kilimanjaro on clear days and has well-developed infrastructure for climbers. Moshi features numerous hotels, restaurants, gear rental shops, and climbing companies. The town has a relaxed atmosphere and serves as a perfect base for pre and post-climb stays. It\'s also close to Kilimanjaro International Airport, making it easily accessible.',
                'featured_image_url' => 'images/hero-slider/kilimanjaro-climbing.jpg',
                'image_gallery' => [
                    'images/tours/kilimanjaro-featured.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Northern Tanzania',
                'city' => 'Moshi',
                'category' => 'Cities',
                'price' => 80,
                'price_display' => 'Starting from $80 per person',
                'duration' => '1-2 days',
                'rating' => 4.2,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Moshi - Kilimanjaro Base Town | Lau Paradise Adventures',
                'meta_description' => 'Moshi, the base town for Mount Kilimanjaro climbs. Perfect starting point for your Kilimanjaro adventure.',
                'meta_keywords' => 'Moshi, Kilimanjaro, mountain climbing, Tanzania',
                'og_image_url' => 'images/hero-slider/kilimanjaro-climbing.jpg',
                'display_order' => 15,
            ],
            [
                'name' => 'Dar es Salaam',
                'slug' => 'dar-es-salaam',
                'short_description' => 'Tanzania\'s largest city and commercial hub, gateway to southern circuit and Zanzibar.',
                'full_description' => 'Dar es Salaam is Tanzania\'s largest city and main commercial hub. While not a traditional tourist destination, it serves as an important gateway to the southern circuit parks (Selous, Ruaha, Mikumi) and Zanzibar. The city offers good accommodation, restaurants serving international and local cuisine, and shopping opportunities. Key attractions include the National Museum, Village Museum, and nearby beaches. The city has excellent flight connections and serves as a transit point for many travelers.',
                'featured_image_url' => 'images/zanzibar_home.jpg',
                'image_gallery' => [
                    'images/hero-slider/zanzibar-beach.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Coastal Tanzania',
                'city' => 'Dar es Salaam',
                'category' => 'Cities',
                'price' => 120,
                'price_display' => 'Starting from $120 per person',
                'duration' => '1-2 days',
                'rating' => 4.0,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Dar es Salaam - Gateway to Southern Circuit | Lau Paradise Adventures',
                'meta_description' => 'Dar es Salaam, Tanzania\'s largest city. Gateway to southern circuit parks and Zanzibar.',
                'meta_keywords' => 'Dar es Salaam, Tanzania, southern circuit, gateway',
                'og_image_url' => 'images/zanzibar_home.jpg',
                'display_order' => 16,
            ],
            // Additional Destinations
            [
                'name' => 'Gombe Stream National Park',
                'slug' => 'gombe-stream-national-park',
                'short_description' => 'Famous for chimpanzee tracking and Jane Goodall\'s research site on the shores of Lake Tanganyika.',
                'full_description' => 'Gombe Stream National Park is one of Tanzania\'s smallest national parks but is world-famous for chimpanzee research. Jane Goodall conducted her groundbreaking research here, and the park continues to be an important research site. The park offers chimpanzee tracking experiences, allowing visitors to observe these fascinating primates in their natural habitat. The park is located on the shores of Lake Tanganyika and offers beautiful scenery in addition to wildlife viewing.',
                'featured_image_url' => 'images/hero-slider/animal-movement.jpg',
                'image_gallery' => [
                    'images/hero-slider/group-of-animals.jpg',
                    'images/safari_home-1.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Western Tanzania',
                'city' => 'Gombe',
                'category' => 'National Parks',
                'price' => 550,
                'price_display' => 'Starting from $550 per person',
                'duration' => '2-3 days',
                'rating' => 4.6,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Gombe Stream - Chimpanzee Tracking | Lau Paradise Adventures',
                'meta_description' => 'Visit Gombe Stream National Park for chimpanzee tracking. Site of Jane Goodall\'s famous research on Lake Tanganyika.',
                'meta_keywords' => 'Gombe Stream, chimpanzees, Jane Goodall, Lake Tanganyika',
                'og_image_url' => 'images/hero-slider/animal-movement.jpg',
                'display_order' => 17,
            ],
            [
                'name' => 'Mahale Mountains National Park',
                'slug' => 'mahale-mountains-national-park',
                'short_description' => 'Remote park on Lake Tanganyika, home to one of Africa\'s largest chimpanzee populations.',
                'full_description' => 'Mahale Mountains National Park is one of Africa\'s most remote and pristine parks, located on the shores of Lake Tanganyika. The park is home to one of Africa\'s largest chimpanzee populations, with over 1,000 individuals. Accessible only by boat or small aircraft, Mahale offers an exclusive and authentic wilderness experience. The park features beautiful mountain scenery, pristine beaches, and excellent chimpanzee tracking opportunities. It\'s a true adventure destination for serious wildlife enthusiasts.',
                'featured_image_url' => 'images/hero-slider/group-of-animals.jpg',
                'image_gallery' => [
                    'images/hero-slider/animal-movement.jpg',
                    'images/safari_home-1.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Western Tanzania',
                'city' => 'Mahale',
                'category' => 'National Parks',
                'price' => 1200,
                'price_display' => 'Starting from $1,200 per person',
                'duration' => '4-6 days',
                'rating' => 4.8,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Mahale Mountains - Chimpanzee Paradise | Lau Paradise Adventures',
                'meta_description' => 'Explore Mahale Mountains National Park. Remote wilderness with large chimpanzee populations on Lake Tanganyika.',
                'meta_keywords' => 'Mahale Mountains, chimpanzees, Lake Tanganyika, remote safari',
                'og_image_url' => 'images/hero-slider/group-of-animals.jpg',
                'display_order' => 18,
            ],
            [
                'name' => 'Katavi National Park',
                'slug' => 'katavi-national-park',
                'short_description' => 'Remote and wild park with massive hippo and crocodile populations during the dry season.',
                'full_description' => 'Katavi National Park is one of Tanzania\'s most remote and least-visited parks, offering a true wilderness experience. The park is famous for its massive hippo and crocodile populations, especially during the dry season when animals congregate around remaining water sources. Katavi offers excellent wildlife viewing including large herds of buffalo, elephants, and various predators. The park is accessible by small aircraft and offers an exclusive safari experience away from all crowds.',
                'featured_image_url' => 'images/safari_home-1.jpg',
                'image_gallery' => [
                    'images/hero-slider/safari-adventure.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Western Tanzania',
                'city' => 'Katavi',
                'category' => 'National Parks',
                'price' => 650,
                'price_display' => 'Starting from $650 per person',
                'duration' => '3-4 days',
                'rating' => 4.7,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Katavi National Park - Remote Wilderness | Lau Paradise Adventures',
                'meta_description' => 'Discover Katavi National Park, one of Tanzania\'s most remote parks. Massive hippo populations and true wilderness.',
                'meta_keywords' => 'Katavi, national park, remote safari, hippos, Tanzania',
                'og_image_url' => 'images/safari_home-1.jpg',
                'display_order' => 19,
            ],
            [
                'name' => 'Mafia Island',
                'slug' => 'mafia-island',
                'short_description' => 'Pristine island paradise with world-class diving, whale sharks, and untouched beaches.',
                'full_description' => 'Mafia Island is a pristine and less-developed alternative to Zanzibar, offering world-class diving and untouched natural beauty. The island is part of the Mafia Island Marine Park, which protects one of the largest reef systems in the Indian Ocean. Mafia is famous for whale shark encounters (seasonal), excellent diving, and pristine beaches. The island offers a more exclusive and authentic experience compared to Zanzibar, perfect for travelers seeking tranquility and world-class marine experiences.',
                'featured_image_url' => 'images/hero-slider/zanzibar-beach.jpg',
                'image_gallery' => [
                    'images/zanzibar_home.jpg',
                    'images/hero-slider/morning.jpg'
                ],
                'country' => 'Tanzania',
                'region' => 'Coastal Tanzania',
                'city' => 'Mafia Island',
                'category' => 'Beaches',
                'price' => 800,
                'price_display' => 'Starting from $800 per person',
                'duration' => '4-7 days',
                'rating' => 4.7,
                'is_active' => true,
                'is_featured' => false,
                'meta_title' => 'Mafia Island - Diving & Whale Sharks | Lau Paradise Adventures',
                'meta_description' => 'Experience Mafia Island, pristine paradise with world-class diving, whale sharks, and untouched beaches.',
                'meta_keywords' => 'Mafia Island, diving, whale sharks, marine park, Tanzania',
                'og_image_url' => 'images/hero-slider/zanzibar-beach.jpg',
                'display_order' => 20,
            ],
        ];

        foreach ($destinations as $destinationData) {
            HomepageDestination::updateOrCreate(
                ['slug' => $destinationData['slug']],
                $destinationData
            );
        }

        $this->command->info('Successfully seeded ' . count($destinations) . ' homepage destinations!');
    }
}






