<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tour;
use App\Models\Destination;
use Illuminate\Support\Str;

class TanzaniaSpecialistToursSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create destinations
        $serengeti = Destination::firstOrCreate(
            ['slug' => 'serengeti'],
            ['name' => 'Serengeti National Park', 'slug' => 'serengeti']
        );
        
        $ngorongoro = Destination::firstOrCreate(
            ['slug' => 'ngorongoro'],
            ['name' => 'Ngorongoro Crater', 'slug' => 'ngorongoro']
        );
        
        $tarangire = Destination::firstOrCreate(
            ['slug' => 'tarangire'],
            ['name' => 'Tarangire National Park', 'slug' => 'tarangire']
        );
        
        $manyara = Destination::firstOrCreate(
            ['slug' => 'manyara'],
            ['name' => 'Lake Manyara', 'slug' => 'manyara']
        );
        
        $kilimanjaro = Destination::firstOrCreate(
            ['slug' => 'kilimanjaro'],
            ['name' => 'Mount Kilimanjaro', 'slug' => 'kilimanjaro']
        );
        
        $zanzibar = Destination::firstOrCreate(
            ['slug' => 'zanzibar'],
            ['name' => 'Zanzibar', 'slug' => 'zanzibar']
        );

        $tours = [
            // Safari + Zanzibar Packages
            [
                'name' => '11 Days Safari & Zanzibar - Best of Both Worlds',
                'slug' => '11-days-safari-zanzibar',
                'destination_id' => $serengeti->id,
                'short_description' => 'Experience the best of Tanzania: incredible wildlife safaris and pristine Zanzibar beaches in one unforgettable journey.',
                'description' => 'This comprehensive 11-day adventure combines the thrill of Tanzania\'s most iconic national parks with the relaxation of Zanzibar\'s tropical paradise. Witness the Big Five in Serengeti, explore the Ngorongoro Crater, and unwind on Zanzibar\'s white sand beaches.',
                'long_description' => 'This 11-day journey offers the perfect blend of wildlife adventure and beach relaxation. Start with an incredible safari experience through Tanzania\'s most famous national parks, where you\'ll witness the Big Five and the Great Migration. Then, fly to Zanzibar for a relaxing beach holiday on one of the world\'s most beautiful islands. This package is perfect for travelers who want to experience both the wild side and the tranquil side of Tanzania. Our expert guides ensure optimal wildlife viewing, while our carefully selected accommodations provide comfort and authenticity. The itinerary is designed to maximize your experience while allowing time for relaxation and cultural immersion.',
                'duration_days' => 11,
                'duration_nights' => 10,
                'start_location' => 'Arusha',
                'end_location' => 'Zanzibar',
                'tour_type' => 'Private',
                'max_group_size' => 6,
                'min_age' => 5,
                'price' => 2126,
                'starting_price' => 2126,
                'rating' => 4.9,
                'fitness_level' => 'moderate',
                'difficulty_level' => 'Easy',
                'image_url' => 'images/tours/safari-zanzibar-11.jpg',
                'gallery_images' => [
                    'images/11-Days-Safari-trip-Tanzania-Zanzibar-1536x1024.jpg',
                    'images/safari_home-1.jpg',
                    'images/Serengetei-NP-2.jpeg',
                    'images/zanzibar_home.jpg'
                ],
                'highlights' => [
                    'Witness the Big Five in Serengeti National Park',
                    'Explore the world-famous Ngorongoro Crater',
                    'Game drives in Tarangire and Lake Manyara',
                    'Relax on Zanzibar\'s pristine beaches',
                    'Stone Town cultural tour',
                    'Spice plantation visit',
                    'Private guide and vehicle throughout',
                    'Luxury tented camps and beach resorts',
                    'Sunset game drives in Serengeti',
                    'Traditional Swahili cuisine experience'
                ],
                'inclusions' => [
                    'All park entry fees and conservation fees',
                    'Professional English-speaking guide with extensive wildlife knowledge',
                    'Private 4x4 safari vehicle with pop-up roof and charging ports',
                    'Accommodation in luxury tented camps and beach resort',
                    'All meals during safari (breakfast, lunch, dinner)',
                    'Breakfast at beach resort',
                    'Domestic flight to Zanzibar (Arusha to Zanzibar)',
                    'Airport transfers (pickup and drop-off)',
                    'Unlimited drinking water and soft drinks during safari',
                    'Binoculars for wildlife viewing',
                    '24/7 support from our local team'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees (approximately $50-100 depending on nationality)',
                    'Travel insurance (mandatory)',
                    'Tips and gratuities (recommended $15-20 per person per day)',
                    'Alcoholic beverages',
                    'Personal expenses and souvenirs',
                    'Optional activities (hot air balloon, diving, etc.)',
                    'Lunch and dinner in Zanzibar (except breakfast)',
                    'Items of personal nature'
                ],
                'terms_conditions' => 'Booking requires 30% deposit. Full payment due 30 days before departure. Cancellation fees apply: 30+ days: 20%, 15-29 days: 50%, 7-14 days: 75%, less than 7 days: 100%. Prices subject to change based on park fees and accommodation availability.',
                'cancellation_policy' => 'Free cancellation up to 30 days before departure (minus 5% processing fee). 15-29 days: 50% refund. 7-14 days: 25% refund. Less than 7 days: No refund. Travel insurance recommended.',
                'important_notes' => 'Yellow fever vaccination certificate required. Malaria prophylaxis recommended. Passport valid for at least 6 months required. Travel insurance mandatory. Children under 5 may have restrictions in some parks. Weather-dependent activities may be modified.',
                'meta_title' => '11 Days Safari & Zanzibar Tour - Best of Tanzania | Lau Paradise Adventures',
                'meta_description' => 'Experience the ultimate Tanzania adventure: 11 days combining incredible wildlife safaris in Serengeti, Ngorongoro, and Tarangire with pristine Zanzibar beaches. Private tours with expert guides.',
                'meta_keywords' => 'Tanzania safari, Zanzibar beach, Serengeti, Ngorongoro, Big Five, wildlife safari, beach holiday, Tanzania tour',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            [
                'name' => '15 Days Safari & Zanzibar - Travel at Your Own Pace',
                'slug' => '15-days-safari-zanzibar',
                'destination_id' => $serengeti->id,
                'short_description' => 'An extended 15-day journey through Tanzania\'s best national parks and Zanzibar, perfect for travelers who want to explore at a relaxed pace.',
                'description' => 'This comprehensive 15-day adventure gives you ample time to explore Tanzania\'s most spectacular destinations. Enjoy extended game drives, multiple nights in each park, and a longer stay on Zanzibar to truly immerse yourself in the beauty of Tanzania.',
                'long_description' => 'Perfect for travelers who prefer a more relaxed pace, this 15-day journey allows you to fully experience Tanzania\'s wonders. Spend multiple nights in each national park for better wildlife viewing opportunities, enjoy extended game drives, and have plenty of time to relax and explore Zanzibar. This itinerary is ideal for photographers, nature enthusiasts, and anyone who wants to truly connect with Tanzania\'s natural beauty. With extended time in each location, you\'ll have opportunities for early morning and late afternoon game drives, cultural interactions, and complete relaxation.',
                'duration_days' => 15,
                'duration_nights' => 14,
                'start_location' => 'Arusha',
                'end_location' => 'Zanzibar',
                'tour_type' => 'Private',
                'max_group_size' => 6,
                'min_age' => 5,
                'price' => 2934,
                'starting_price' => 2934,
                'rating' => 4.8,
                'fitness_level' => 'moderate',
                'difficulty_level' => 'Easy',
                'image_url' => 'images/tours/safari-zanzibar-15.jpg',
                'gallery_images' => [
                    'images/15-Days-trip-Tanzania-Zanzibar-1536x1024.webp',
                    'images/13-Days-Safari-Zanzibar-holiday-1518x1536.jpg',
                    'images/safari_home-1.jpg',
                    'images/zanzibar_home.jpg',
                    'images/hero-slider/zanzibar-beach.jpg'
                ],
                'highlights' => [
                    'Extended stays in Serengeti, Ngorongoro, and Tarangire',
                    'Multiple game drives for optimal wildlife viewing',
                    'Great Migration viewing opportunities',
                    'Extended Zanzibar beach stay',
                    'Stone Town exploration',
                    'Spice tour and local village visits',
                    'Snorkeling and water activities',
                    'Private guide and vehicle',
                    'Photography workshops and tips',
                    'Cultural immersion experiences'
                ],
                'inclusions' => [
                    'All park entry fees and conservation fees',
                    'Professional English-speaking guide with photography expertise',
                    'Private 4x4 safari vehicle with pop-up roof and bean bags for photography',
                    'Luxury tented camps and beach resort accommodation',
                    'All meals during safari (breakfast, lunch, dinner)',
                    'Breakfast at beach resort',
                    'Domestic flight to Zanzibar',
                    'All transfers and airport pickups',
                    'Unlimited drinking water and soft drinks',
                    'Binoculars and field guides',
                    '24/7 support from our local team'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance',
                    'Tips and gratuities',
                    'Alcoholic beverages',
                    'Personal expenses',
                    'Optional activities',
                    'Lunch and dinner in Zanzibar'
                ],
                'terms_conditions' => 'Booking requires 30% deposit. Full payment due 30 days before departure. Cancellation fees apply: 30+ days: 20%, 15-29 days: 50%, 7-14 days: 75%, less than 7 days: 100%.',
                'cancellation_policy' => 'Free cancellation up to 30 days before departure (minus 5% processing fee). 15-29 days: 50% refund. 7-14 days: 25% refund. Less than 7 days: No refund.',
                'important_notes' => 'Yellow fever vaccination certificate required. Malaria prophylaxis recommended. Passport valid for at least 6 months required. Travel insurance mandatory.',
                'meta_title' => '15 Days Extended Safari & Zanzibar Tour - Tanzania | Lau Paradise Adventures',
                'meta_description' => 'Extended 15-day Tanzania safari and Zanzibar beach holiday. Multiple nights in each park for optimal wildlife viewing. Perfect for photographers and nature enthusiasts.',
                'meta_keywords' => 'extended Tanzania safari, Zanzibar, photography safari, wildlife viewing, Serengeti, Ngorongoro',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            // Safari Packages
            [
                'name' => '9 Days Safari - Wildebeest Migration and Mara River Crossing',
                'slug' => '9-days-migration-safari',
                'destination_id' => $serengeti->id,
                'short_description' => 'Witness one of nature\'s greatest spectacles: the Great Migration and the dramatic Mara River crossing in Serengeti.',
                'description' => 'This 9-day safari is specifically designed to witness the Great Migration, one of the most incredible wildlife events on Earth. Watch thousands of wildebeest and zebra cross the Mara River, and experience the Big Five in their natural habitat.',
                'long_description' => 'The Great Migration is one of the most spectacular wildlife events on the planet. This 9-day safari takes you to the heart of the action, where you\'ll witness thousands of wildebeest and zebra making their dramatic river crossings. Combined with game drives in Serengeti, Ngorongoro, and Tarangire, this is a once-in-a-lifetime wildlife experience. Your expert guide will position you at the best viewing spots to witness this incredible natural phenomenon. The itinerary is carefully timed to maximize your chances of witnessing river crossings, with extended time in the northern Serengeti where the action occurs.',
                'duration_days' => 9,
                'duration_nights' => 8,
                'start_location' => 'Arusha',
                'end_location' => 'Arusha',
                'tour_type' => 'Private',
                'max_group_size' => 6,
                'min_age' => 8,
                'price' => 2289,
                'starting_price' => 2289,
                'rating' => 4.9,
                'fitness_level' => 'moderate',
                'difficulty_level' => 'Easy',
                'image_url' => 'images/tours/migration-safari-9.jpg',
                'gallery_images' => [
                    'images/9-Days-Safari-vacation-Tanzania-Wildebeest-migration-1536x962.webp',
                    'images/Mara-River-3-1536x1024.jpg',
                    'images/Serengetei-NP-2.jpeg',
                    'images/safari_home-1.jpg'
                ],
                'highlights' => [
                    'Witness the Great Migration river crossing',
                    'Multiple game drives in Serengeti (northern region)',
                    'Big Five viewing in Ngorongoro Crater',
                    'Elephant herds in Tarangire',
                    'Bird watching at Lake Manyara',
                    'Professional wildlife photography opportunities',
                    'Luxury tented camps in prime migration locations',
                    'Expert guide with migration tracking knowledge',
                    'Extended time at river crossing points',
                    'Predator action during migration'
                ],
                'inclusions' => [
                    'All park entry fees and conservation fees',
                    'Professional English-speaking guide with migration expertise',
                    'Private 4x4 safari vehicle with pop-up roof',
                    'Luxury tented camp accommodation in prime locations',
                    'All meals (breakfast, lunch, dinner)',
                    'Airport transfers',
                    'Unlimited drinking water and soft drinks',
                    'Migration tracking and positioning expertise',
                    'Binoculars for wildlife viewing',
                    '24/7 support'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance',
                    'Tips and gratuities',
                    'Alcoholic beverages',
                    'Personal expenses',
                    'Optional activities'
                ],
                'terms_conditions' => 'Booking requires 30% deposit. Full payment due 30 days before departure. Migration timing is nature-dependent and cannot be guaranteed, though itinerary is optimized for peak season.',
                'cancellation_policy' => 'Free cancellation up to 30 days before departure (minus 5% processing fee). 15-29 days: 50% refund. 7-14 days: 25% refund. Less than 7 days: No refund.',
                'important_notes' => 'Migration timing varies annually. Best viewing typically July-October. River crossings cannot be guaranteed but itinerary maximizes opportunities. Yellow fever vaccination required. Malaria prophylaxis recommended.',
                'meta_title' => '9 Days Great Migration Safari - Mara River Crossing | Lau Paradise Adventures',
                'meta_description' => 'Witness the Great Migration and Mara River crossing in Serengeti. 9-day safari designed for optimal migration viewing with expert guides and prime locations.',
                'meta_keywords' => 'Great Migration safari, Mara River crossing, wildebeest migration, Serengeti migration, Tanzania migration safari',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            [
                'name' => '7 Days Safari - Visit Two of Africa\'s Seven Natural Wonders',
                'slug' => '7-days-natural-wonders',
                'destination_id' => $serengeti->id,
                'short_description' => 'Experience two of Africa\'s Seven Natural Wonders: Serengeti National Park and Ngorongoro Crater in one incredible week.',
                'description' => 'This 7-day safari takes you to two of Africa\'s most iconic natural wonders. Explore the endless plains of Serengeti and descend into the world\'s largest intact caldera at Ngorongoro.',
                'long_description' => 'Serengeti National Park and Ngorongoro Crater are both recognized as two of Africa\'s Seven Natural Wonders. This carefully crafted 7-day itinerary ensures you experience the best of both. From the vast savannas of Serengeti, home to the Great Migration, to the wildlife-rich Ngorongoro Crater, this safari showcases Tanzania\'s most spectacular landscapes and wildlife. With multiple game drives in each location, you\'ll have ample opportunities to witness the Big Five and experience the unique ecosystems of these natural wonders.',
                'duration_days' => 7,
                'duration_nights' => 6,
                'start_location' => 'Arusha',
                'end_location' => 'Arusha',
                'tour_type' => 'Private',
                'max_group_size' => 6,
                'min_age' => 8,
                'price' => 1588,
                'starting_price' => 1588,
                'rating' => 4.8,
                'fitness_level' => 'moderate',
                'difficulty_level' => 'Easy',
                'image_url' => 'images/tours/natural-wonders-7.jpg',
                'gallery_images' => [
                    'images/7-DAYS-SAFARI-TANZANIA--1536x1024.webp',
                    'images/Serengetei-NP-2.jpeg',
                    'images/safari_home-1.jpg'
                ],
                'highlights' => [
                    'Serengeti National Park - Africa\'s Natural Wonder',
                    'Ngorongoro Crater - World\'s largest intact caldera',
                    'Big Five viewing in both locations',
                    'Great Migration opportunities (seasonal)',
                    'Tarangire elephant herds',
                    'Lake Manyara bird watching (400+ species)',
                    'Luxury tented camps and lodges',
                    'Expert local guides with extensive knowledge',
                    'Multiple game drives in each park',
                    'Stunning landscape photography opportunities'
                ],
                'inclusions' => [
                    'All park entry fees and conservation fees',
                    'Professional English-speaking guide',
                    'Private 4x4 vehicle with pop-up roof',
                    'Luxury tented camp and lodge accommodation',
                    'All meals (breakfast, lunch, dinner)',
                    'Airport transfers',
                    'Unlimited drinking water and soft drinks',
                    'Binoculars for wildlife viewing',
                    '24/7 support'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance',
                    'Tips and gratuities',
                    'Alcoholic beverages',
                    'Personal expenses',
                    'Optional activities'
                ],
                'terms_conditions' => 'Booking requires 30% deposit. Full payment due 30 days before departure. Natural wonders access subject to park regulations.',
                'cancellation_policy' => 'Free cancellation up to 30 days before departure (minus 5% processing fee). 15-29 days: 50% refund. 7-14 days: 25% refund. Less than 7 days: No refund.',
                'important_notes' => 'Two of Africa\'s Seven Natural Wonders. Minimum age 8 years. Yellow fever vaccination required. Malaria prophylaxis recommended. Weather-dependent activities may be modified.',
                'meta_title' => '7 Days Safari - Two of Africa\'s Natural Wonders | Lau Paradise Adventures',
                'meta_description' => 'Experience two of Africa\'s Seven Natural Wonders: Serengeti National Park and Ngorongoro Crater. 7-day safari with Big Five viewing and stunning landscapes.',
                'meta_keywords' => 'Africa natural wonders, Serengeti, Ngorongoro Crater, Tanzania safari, Big Five, natural wonders safari',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            // Kilimanjaro Climbing
            [
                'name' => 'Kilimanjaro Climbing - Marangu Route',
                'slug' => 'kilimanjaro-marangu-route',
                'destination_id' => $kilimanjaro->id,
                'short_description' => 'Conquer Africa\'s highest peak via the Marangu Route, known as the "Coca-Cola Route" for its comfort and popularity.',
                'description' => 'The Marangu Route is Kilimanjaro\'s most popular and comfortable route, featuring hut accommodation instead of camping. This 6-day ascent offers the best chance of summit success with gradual acclimatization.',
                'long_description' => 'The Marangu Route, also known as the "Coca-Cola Route," is Kilimanjaro\'s most popular climbing route. It\'s the only route that offers hut accommodation, making it more comfortable than camping routes. The 6-day itinerary provides excellent acclimatization, increasing your chances of reaching Uhuru Peak. Our certified guides, porters, and comprehensive safety equipment ensure a safe and memorable climb. The route takes you through diverse ecosystems from rainforest to alpine desert, culminating in the arctic summit zone.',
                'duration_days' => 6,
                'duration_nights' => 5,
                'start_location' => 'Moshi',
                'end_location' => 'Moshi',
                'tour_type' => 'Group',
                'max_group_size' => 12,
                'min_age' => 16,
                'price' => 1776,
                'starting_price' => 1776,
                'rating' => 4.7,
                'fitness_level' => 'high',
                'difficulty_level' => 'Hard',
                'image_url' => 'images/tours/kilimanjaro-marangu.jpg',
                'gallery_images' => [
                    'images/hero-slider/kilimanjaro-climbing.jpg',
                    'images/hero-slider/kilimanjaro-climbing4.jpg',
                    'images/tours/kilimanjaro-featured.jpg'
                ],
                'highlights' => [
                    'Summit Africa\'s highest peak (5,895m / 19,341ft)',
                    'Hut accommodation (no camping required)',
                    'Certified ethical climbing guides (Wilderness First Responder)',
                    'Gradual acclimatization with 6-day itinerary',
                    'Stunning mountain views and diverse ecosystems',
                    'Professional safety equipment (oxygen, pulse oximeters)',
                    'Porter support (carry up to 20kg per person)',
                    'Summit certificate and achievement recognition',
                    'Small group size for personalized attention',
                    'Pre-climb fitness assessment and briefing'
                ],
                'inclusions' => [
                    'All park fees, permits, and rescue fees',
                    'Certified mountain guide (Wilderness First Responder certified)',
                    'Assistant guides (1 guide per 2 climbers)',
                    'Porters (carry up to 20kg per person)',
                    'Hut accommodation (shared dormitory style)',
                    'All meals on the mountain (nutritious, high-energy)',
                    'Camping equipment (if needed for flexibility)',
                    'Safety equipment (portable oxygen, pulse oximeters, comprehensive first aid)',
                    'Airport transfers',
                    'Pre-climb briefing and gear check',
                    'Accommodation before and after climb (1 night each)',
                    '24/7 support from base camp'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance (mandatory with high-altitude coverage)',
                    'Tips for guides and porters (recommended $200-300)',
                    'Personal climbing gear (rental available)',
                    'Additional accommodation',
                    'Alcoholic beverages',
                    'Personal expenses'
                ],
                'terms_conditions' => 'Booking requires 50% deposit. Full payment due 60 days before departure. Medical clearance required. Minimum age 16. Physical fitness assessment recommended.',
                'cancellation_policy' => 'Free cancellation up to 60 days before departure (minus 10% processing fee). 30-59 days: 50% refund. 15-29 days: 25% refund. Less than 15 days: No refund.',
                'important_notes' => 'High altitude climbing requires excellent physical fitness. Medical clearance mandatory. Altitude sickness possible. Weather conditions can affect summit attempts. Proper gear essential. Travel insurance with high-altitude coverage required.',
                'meta_title' => 'Kilimanjaro Marangu Route - 6 Days Climb | Lau Paradise Adventures',
                'meta_description' => 'Climb Kilimanjaro via Marangu Route - 6 days with hut accommodation. Certified guides, safety equipment, and highest success rate. Summit Africa\'s highest peak.',
                'meta_keywords' => 'Kilimanjaro Marangu Route, Kilimanjaro climbing, Mount Kilimanjaro, Tanzania climbing, high altitude trekking, Coca-Cola Route',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            [
                'name' => 'Kilimanjaro Climbing - Machame Route',
                'slug' => 'kilimanjaro-machame-route',
                'destination_id' => $kilimanjaro->id,
                'short_description' => 'Challenge yourself on the Machame Route, Kilimanjaro\'s most scenic and popular camping route, known as the "Whiskey Route".',
                'description' => 'The Machame Route offers stunning scenery and excellent acclimatization. This 7-day climb takes you through diverse ecosystems and provides the best views of Kilimanjaro.',
                'long_description' => 'The Machame Route, nicknamed the "Whiskey Route," is considered Kilimanjaro\'s most scenic route. This 7-day climb takes you through five distinct climate zones, from rainforest to arctic summit. The route offers excellent acclimatization and stunning views throughout. Camping under the stars adds to the adventure, and our experienced guides ensure your safety and success. The extended 7-day itinerary significantly increases summit success rates compared to shorter routes.',
                'duration_days' => 7,
                'duration_nights' => 6,
                'start_location' => 'Moshi',
                'end_location' => 'Moshi',
                'tour_type' => 'Group',
                'max_group_size' => 12,
                'min_age' => 16,
                'price' => 2578,
                'starting_price' => 2578,
                'rating' => 4.8,
                'fitness_level' => 'high',
                'difficulty_level' => 'Hard',
                'image_url' => 'images/tours/kilimanjaro-machame.jpg',
                'gallery_images' => [
                    'images/hero-slider/kilimanjaro-climbing.jpg',
                    'images/hero-slider/kilimanjaro-climbing4.jpg',
                    'images/tours/kilimanjaro-featured.jpg',
                    'images/tours/kilimanjaro-marangu.jpg'
                ],
                'highlights' => [
                    'Summit Uhuru Peak (5,895m / 19,341ft)',
                    'Most scenic route on Kilimanjaro',
                    'Camping under the stars',
                    'Five distinct climate zones',
                    'Excellent acclimatization with 7-day itinerary',
                    'Certified ethical guides (Wilderness First Responder)',
                    'Professional support team (guides, porters, cooks)',
                    'Summit certificate and achievement recognition',
                    'Higher success rate than shorter routes',
                    'Stunning sunrise from summit'
                ],
                'inclusions' => [
                    'All park fees, permits, and rescue fees',
                    'Certified mountain guides (Wilderness First Responder certified)',
                    'Assistant guides (1 guide per 2 climbers)',
                    'Porters (carry up to 20kg per person)',
                    'Professional cook and kitchen team',
                    'Camping equipment (tents, sleeping mats, mess tent)',
                    'All meals on the mountain (nutritious, high-energy)',
                    'Safety equipment (portable oxygen, pulse oximeters, comprehensive first aid)',
                    'Airport transfers',
                    'Pre-climb briefing and gear check',
                    'Accommodation before and after climb (1 night each)',
                    '24/7 support from base camp'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance (mandatory with high-altitude coverage)',
                    'Tips for team (recommended $250-350)',
                    'Personal climbing gear (rental available)',
                    'Additional accommodation',
                    'Alcoholic beverages',
                    'Personal expenses'
                ],
                'terms_conditions' => 'Booking requires 50% deposit. Full payment due 60 days before departure. Medical clearance required. Minimum age 16. Physical fitness assessment recommended.',
                'cancellation_policy' => 'Free cancellation up to 60 days before departure (minus 10% processing fee). 30-59 days: 50% refund. 15-29 days: 25% refund. Less than 15 days: No refund.',
                'important_notes' => 'High altitude climbing requires excellent physical fitness. Medical clearance mandatory. Altitude sickness possible. Weather conditions can affect summit attempts. Proper gear essential. Travel insurance with high-altitude coverage required.',
                'meta_title' => 'Kilimanjaro Machame Route - 7 Days Most Scenic Climb | Lau Paradise Adventures',
                'meta_description' => 'Climb Kilimanjaro via Machame Route - 7 days, most scenic route. Camping under stars, five climate zones, certified guides, and high success rate.',
                'meta_keywords' => 'Kilimanjaro Machame Route, Whiskey Route, Kilimanjaro climbing, Mount Kilimanjaro, Tanzania climbing, camping route',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            // Zanzibar Packages
            [
                'name' => '10 Days Zanzibar - Find Out What Paradise Looks Like',
                'slug' => '10-days-zanzibar-paradise',
                'destination_id' => $zanzibar->id,
                'short_description' => 'Discover Zanzibar\'s pristine beaches, rich culture, and tropical paradise in this comprehensive 10-day island escape.',
                'description' => 'Experience the best of Zanzibar with this 10-day itinerary. From historic Stone Town to pristine beaches, spice plantations to water activities, discover why Zanzibar is called paradise.',
                'long_description' => 'Zanzibar is truly a tropical paradise. This 10-day journey takes you through the island\'s highlights: explore the UNESCO World Heritage Site of Stone Town, visit spice plantations, relax on pristine beaches, enjoy water activities, and immerse yourself in the rich Swahili culture. Perfect for honeymooners, families, or anyone seeking a perfect beach holiday. The extended duration allows you to truly unwind and experience the island\'s laid-back atmosphere while exploring its cultural and natural treasures.',
                'duration_days' => 10,
                'duration_nights' => 9,
                'start_location' => 'Zanzibar Airport',
                'end_location' => 'Zanzibar Airport',
                'tour_type' => 'Private',
                'max_group_size' => 8,
                'min_age' => 3,
                'price' => 605,
                'starting_price' => 605,
                'rating' => 4.9,
                'fitness_level' => 'low',
                'difficulty_level' => 'Easy',
                'image_url' => 'images/tours/zanzibar-10.jpg',
                'gallery_images' => [
                    'images/zanzibar_home.jpg',
                    'images/hero-slider/zanzibar-beach.jpg',
                    'images/11-Days-Safari-trip-Tanzania-Zanzibar-1536x1024.jpg',
                    'images/safari_home-1.jpg',
                    'images/13-Days-Safari-Zanzibar-holiday-1518x1536.jpg'
                ],
                'highlights' => [
                    'Stone Town UNESCO World Heritage Site',
                    'Pristine white sand beaches',
                    'Spice plantation tour with cooking class',
                    'Snorkeling and diving in crystal-clear waters',
                    'Dolphin watching and swimming',
                    'Jozani Forest (endemic red colobus monkeys)',
                    'Traditional dhow sailing at sunset',
                    'Swahili culture immersion and local interactions',
                    'Beachside relaxation and water sports',
                    'Authentic local cuisine experiences'
                ],
                'inclusions' => [
                    'Airport transfers',
                    'Beach resort accommodation',
                    'Breakfast daily',
                    'Stone Town guided tour',
                    'Spice plantation tour with cooking demonstration',
                    'Jozani Forest visit with guide',
                    'Dhow sailing trip (half day)',
                    'Snorkeling equipment and trip',
                    'Dolphin watching excursion',
                    'Cultural village visit',
                    'All entrance fees',
                    '24/7 support'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance',
                    'Lunch and dinner (except breakfast)',
                    'Alcoholic beverages',
                    'Optional activities (scuba diving, etc.)',
                    'Tips and gratuities',
                    'Personal expenses',
                    'Items of personal nature'
                ],
                'terms_conditions' => 'Booking requires 30% deposit. Full payment due 30 days before departure. Beach activities weather-dependent. Children under 5 stay free (sharing with parents).',
                'cancellation_policy' => 'Free cancellation up to 30 days before departure (minus 5% processing fee). 15-29 days: 50% refund. 7-14 days: 25% refund. Less than 7 days: No refund.',
                'important_notes' => 'Perfect for all ages. Minimum age 3. Beach activities weather-dependent. Yellow fever vaccination not required for Zanzibar only. Sun protection essential. Respectful dress required in Stone Town.',
                'meta_title' => '10 Days Zanzibar Paradise - Beach Holiday & Culture | Lau Paradise Adventures',
                'meta_description' => 'Discover Zanzibar paradise: 10 days of pristine beaches, Stone Town UNESCO site, spice tours, snorkeling, and Swahili culture. Perfect beach holiday.',
                'meta_keywords' => 'Zanzibar holiday, Zanzibar beach, Stone Town, spice tour, Zanzibar snorkeling, tropical paradise, Swahili culture',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            // Southern Circuit Safari
            [
                'name' => '10 Days Safari in the South - Perfect for Southern National Parks',
                'slug' => '10-days-southern-safari',
                'destination_id' => $serengeti->id,
                'short_description' => 'Explore Tanzania\'s less-crowded southern circuit, including Selous, Ruaha, and Mikumi National Parks for an authentic wilderness experience.',
                'description' => 'Discover Tanzania\'s hidden gems in the southern circuit. This 10-day safari takes you to Selous Game Reserve, Ruaha National Park, and Mikumi, offering authentic wilderness experiences away from the crowds.',
                'long_description' => 'Tanzania\'s southern circuit offers a more authentic and less-crowded safari experience. This 10-day journey takes you through Selous Game Reserve (Africa\'s largest), Ruaha National Park (known for large elephant herds), and Mikumi National Park. Experience boat safaris, walking safaris, and traditional game drives in some of Tanzania\'s most pristine wilderness areas. This route is perfect for travelers seeking authentic African wilderness without the crowds of the northern circuit.',
                'duration_days' => 10,
                'duration_nights' => 9,
                'start_location' => 'Dar es Salaam',
                'end_location' => 'Dar es Salaam',
                'tour_type' => 'Private',
                'max_group_size' => 6,
                'min_age' => 12,
                'price' => 2827,
                'starting_price' => 2827,
                'rating' => 4.7,
                'fitness_level' => 'moderate',
                'difficulty_level' => 'Medium',
                'image_url' => 'images/tours/southern-safari-10.jpg',
                'gallery_images' => [
                    'images/10-Days-Tanzania-safari-all-northern-parks-in-1-trip-wildebeest-migration-1536x1026.webp',
                    'images/safari_home-1.jpg',
                    'images/Serengetei-NP-2.jpeg'
                ],
                'highlights' => [
                    'Selous Game Reserve - Africa\'s largest',
                    'Ruaha National Park - elephant paradise',
                    'Mikumi National Park',
                    'Boat safaris on Rufiji River',
                    'Walking safaris with armed rangers',
                    'Wild dog viewing opportunities',
                    'Less crowded, authentic experience',
                    'Diverse wildlife and landscapes',
                    'Bird watching (over 400 species)',
                    'Night game drives'
                ],
                'inclusions' => [
                    'All park fees and conservation fees',
                    'Professional English-speaking guide',
                    'Private 4x4 vehicle',
                    'Lodge accommodation',
                    'All meals (breakfast, lunch, dinner)',
                    'Boat safari on Rufiji River',
                    'Walking safari with armed ranger',
                    'Airport transfers',
                    'Drinking water and soft drinks',
                    'Binoculars for wildlife viewing'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance',
                    'Tips and gratuities',
                    'Alcoholic beverages',
                    'Personal expenses',
                    'Optional activities'
                ],
                'terms_conditions' => 'Booking requires 30% deposit. Full payment due 30 days before departure. Walking safaris require minimum age of 12 years.',
                'cancellation_policy' => 'Free cancellation up to 30 days before departure (minus 5% processing fee). 15-29 days: 50% refund. 7-14 days: 25% refund. Less than 7 days: No refund.',
                'important_notes' => 'Walking safaris require good physical fitness. Minimum age 12 for walking safaris. Yellow fever vaccination required. Malaria prophylaxis strongly recommended.',
                'meta_title' => '10 Days Southern Circuit Safari - Selous, Ruaha, Mikumi | Lau Paradise Adventures',
                'meta_description' => 'Explore Tanzania\'s southern circuit: Selous Game Reserve, Ruaha and Mikumi National Parks. Boat safaris, walking safaris, and authentic wilderness experience.',
                'meta_keywords' => 'southern circuit safari, Selous, Ruaha, Mikumi, boat safari, walking safari, Tanzania',
                'availability_status' => 'Available',
                'is_featured' => false,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            // NEW ADVANCED TOURS - Added to reach 15 total
            [
                'name' => '12 Days Luxury Safari Experience - Ultimate Wildlife & Comfort',
                'slug' => '12-days-luxury-safari',
                'destination_id' => $serengeti->id,
                'short_description' => 'Indulge in the ultimate luxury safari experience with premium accommodations, exclusive experiences, and personalized service in Tanzania\'s finest national parks.',
                'description' => 'Experience Tanzania in unparalleled luxury. This 12-day safari combines world-class wildlife viewing with five-star accommodations, private guides, and exclusive experiences. Stay in luxury lodges and tented camps, enjoy private game drives, and savor gourmet cuisine under the African stars.',
                'long_description' => 'This is the ultimate luxury safari experience for discerning travelers. Over 12 days, you\'ll explore Tanzania\'s most iconic national parks while staying in the finest accommodations available. From private suites with panoramic views to luxury tented camps with butler service, every detail is curated for your comfort. Enjoy exclusive experiences like private game drives, bush dinners, sundowners in remote locations, and spa treatments. Our expert guides ensure you witness the best wildlife viewing opportunities while our dedicated team handles every detail of your journey.',
                'duration_days' => 12,
                'duration_nights' => 11,
                'start_location' => 'Arusha',
                'end_location' => 'Arusha',
                'tour_type' => 'Private',
                'max_group_size' => 4,
                'min_age' => 8,
                'price' => 4850,
                'starting_price' => 4850,
                'rating' => 5.0,
                'fitness_level' => 'low',
                'difficulty_level' => 'Easy',
                'image_url' => 'images/safari_home-1.jpg',
                'gallery_images' => [
                    'images/safari_home-1.jpg',
                    'images/Serengetei-NP-2.jpeg',
                    'images/Mara-River-3-1536x1024.jpg',
                    'images/hero-slider/safari-adventure.jpg',
                    'images/DSC05518-1536x1024.jpg'
                ],
                'highlights' => [
                    'Luxury five-star lodges and tented camps',
                    'Private game drives with expert guides',
                    'Exclusive bush dinners under the stars',
                    'Sundowner experiences in remote locations',
                    'Spa treatments and wellness activities',
                    'Gourmet cuisine with premium wines',
                    'Butler service at select properties',
                    'Private airstrip transfers',
                    'Hot air balloon safari (optional)',
                    'Photography workshops with professional photographers'
                ],
                'inclusions' => [
                    'All park entry fees and conservation fees',
                    'Private English-speaking guide with extensive experience',
                    'Private luxury 4x4 vehicle with guaranteed window seats',
                    'Luxury lodge and tented camp accommodation',
                    'All meals (breakfast, lunch, dinner) with premium beverages',
                    'Private bush dinners and sundowner experiences',
                    'Spa treatments (one per person)',
                    'Airport transfers in luxury vehicles',
                    'Unlimited premium beverages (wine, spirits, soft drinks)',
                    'Laundry service',
                    'Binoculars and field guides',
                    '24/7 concierge service',
                    'Travel documentation and support'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance',
                    'Tips and gratuities',
                    'Optional hot air balloon safari ($550 per person)',
                    'Personal expenses and shopping',
                    'Items of personal nature'
                ],
                'terms_conditions' => 'Booking requires 50% deposit. Full payment due 45 days before departure. Premium accommodations subject to availability. Single supplement applies for solo travelers.',
                'cancellation_policy' => 'Free cancellation up to 45 days before departure (minus 5% processing fee). 30-44 days: 50% refund. 15-29 days: 25% refund. Less than 15 days: No refund.',
                'important_notes' => 'Luxury accommodations require early booking. Minimum age 8 years. Yellow fever vaccination required. Travel insurance mandatory. Special dietary requirements must be communicated 30 days in advance.',
                'meta_title' => '12 Days Luxury Safari Tanzania - Premium Wildlife Experience | Lau Paradise Adventures',
                'meta_description' => 'Ultimate luxury safari in Tanzania. 12 days of premium accommodations, private guides, exclusive experiences, and world-class wildlife viewing in Serengeti, Ngorongoro, and Tarangire.',
                'meta_keywords' => 'luxury safari Tanzania, premium safari, five-star safari, luxury lodges, private safari, exclusive Tanzania',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            [
                'name' => '14 Days Photography Safari - Capture Africa\'s Wildlife',
                'slug' => '14-days-photography-safari',
                'destination_id' => $serengeti->id,
                'short_description' => 'A specialized 14-day photography safari designed for serious photographers, with expert guidance, optimal lighting times, and prime wildlife viewing locations.',
                'description' => 'Perfect for photography enthusiasts, this 14-day safari is designed around optimal lighting conditions and prime wildlife viewing. Work with professional wildlife photographers, learn advanced techniques, and capture stunning images of Africa\'s most iconic animals.',
                'long_description' => 'This specialized photography safari is crafted for serious photographers who want to capture Africa\'s wildlife at its best. Over 14 days, you\'ll work with professional wildlife photographers who understand animal behavior, lighting, and composition. The itinerary is designed around golden hour game drives, extended time at prime locations, and opportunities for both wide-angle landscapes and intimate wildlife portraits. Learn advanced photography techniques, post-processing tips, and how to tell compelling visual stories. Accommodations are chosen for their proximity to prime photography locations, and vehicles are equipped with bean bags and camera mounts.',
                'duration_days' => 14,
                'duration_nights' => 13,
                'start_location' => 'Arusha',
                'end_location' => 'Arusha',
                'tour_type' => 'Private',
                'max_group_size' => 4,
                'min_age' => 16,
                'price' => 3890,
                'starting_price' => 3890,
                'rating' => 4.9,
                'fitness_level' => 'moderate',
                'difficulty_level' => 'Medium',
                'image_url' => 'images/Serengetei-NP-2.jpeg',
                'gallery_images' => [
                    'images/Mara-River-3-1536x1024.jpg',
                    'images/DSC05518-1536x1024.jpg',
                    'images/hero-slider/animal-movement.jpg',
                    'images/hero-slider/group-of-animals.jpg'
                ],
                'highlights' => [
                    'Professional wildlife photography guide',
                    'Golden hour and blue hour game drives',
                    'Extended time at prime photography locations',
                    'Photography workshops and technique sessions',
                    'Post-processing and editing tutorials',
                    'Bean bags and camera mounts in vehicles',
                    'Small group size (max 4) for optimal positioning',
                    'Great Migration photography opportunities',
                    'Big Five portrait sessions',
                    'Landscape and wildlife composition training'
                ],
                'inclusions' => [
                    'All park entry fees and conservation fees',
                    'Professional wildlife photography guide',
                    'Private 4x4 vehicle with photography equipment mounts',
                    'Bean bags and camera supports',
                    'Accommodation in photography-optimized locations',
                    'All meals (breakfast, lunch, dinner)',
                    'Extended game drives during optimal lighting',
                    'Photography workshops and tutorials',
                    'Post-processing software guidance',
                    'Airport transfers',
                    'Unlimited drinking water and soft drinks',
                    '24/7 support'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance',
                    'Photography equipment (cameras, lenses, etc.)',
                    'Tips and gratuities',
                    'Alcoholic beverages',
                    'Personal expenses',
                    'Optional hot air balloon photography ($550)'
                ],
                'terms_conditions' => 'Booking requires 30% deposit. Full payment due 30 days before departure. Minimum age 16. Photography equipment not included.',
                'cancellation_policy' => 'Free cancellation up to 30 days before departure (minus 5% processing fee). 15-29 days: 50% refund. 7-14 days: 25% refund. Less than 7 days: No refund.',
                'important_notes' => 'Designed for serious photographers. Participants should have basic photography knowledge. Bring your own camera equipment. Weather-dependent activities may be modified. Yellow fever vaccination required.',
                'meta_title' => '14 Days Photography Safari Tanzania - Wildlife Photography Tour | Lau Paradise Adventures',
                'meta_description' => 'Specialized 14-day photography safari in Tanzania. Professional wildlife photography guide, optimal lighting game drives, and prime locations for capturing Africa\'s wildlife.',
                'meta_keywords' => 'photography safari, wildlife photography, Tanzania photography tour, Serengeti photography, wildlife photography guide',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            [
                'name' => '8 Days Family Safari Adventure - Perfect for All Ages',
                'slug' => '8-days-family-safari',
                'destination_id' => $serengeti->id,
                'short_description' => 'A family-friendly 8-day safari designed for travelers with children, featuring educational activities, shorter game drives, and family-oriented accommodations.',
                'description' => 'Perfect for families with children, this 8-day safari combines incredible wildlife viewing with educational activities, interactive experiences, and accommodations designed for families. Shorter game drives, child-friendly meals, and engaging guides make this ideal for all ages.',
                'long_description' => 'This family-friendly safari is specifically designed for travelers with children, ensuring everyone from toddlers to grandparents has an unforgettable experience. The itinerary includes shorter game drives to accommodate attention spans, educational activities about wildlife and conservation, and interactive experiences like tracking animals, learning about local cultures, and visiting community projects. Accommodations are family-oriented with family rooms, swimming pools, and child-friendly facilities. Our guides are experienced with families and know how to engage children while ensuring adults also have an amazing experience.',
                'duration_days' => 8,
                'duration_nights' => 7,
                'start_location' => 'Arusha',
                'end_location' => 'Arusha',
                'tour_type' => 'Private',
                'max_group_size' => 8,
                'min_age' => 3,
                'price' => 1890,
                'starting_price' => 1890,
                'rating' => 4.8,
                'fitness_level' => 'low',
                'difficulty_level' => 'Easy',
                'image_url' => 'images/safari_home-1.jpg',
                'gallery_images' => [
                    'images/safari_home-1.jpg',
                    'images/hero-slider/safari-adventure.jpg',
                    'images/Tarangire-NP-1.jpeg'
                ],
                'highlights' => [
                    'Family-friendly accommodations with pools',
                    'Shorter game drives suitable for children',
                    'Educational wildlife activities',
                    'Interactive cultural experiences',
                    'Child-friendly meals and dietary options',
                    'Family rooms and connecting accommodations',
                    'Swimming pools at all lodges',
                    'Wildlife tracking and identification games',
                    'Community visits and school interactions',
                    'Experienced family-friendly guides'
                ],
                'inclusions' => [
                    'All park entry fees (children under 5 free)',
                    'Professional English-speaking guide (family-experienced)',
                    'Private 4x4 vehicle with child seats available',
                    'Family-friendly lodge accommodation',
                    'All meals with child-friendly options',
                    'Educational activities and games',
                    'Community visit and cultural interaction',
                    'Airport transfers',
                    'Unlimited drinking water and soft drinks',
                    'Child safety equipment',
                    '24/7 family support'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance',
                    'Tips and gratuities',
                    'Alcoholic beverages',
                    'Personal expenses',
                    'Optional activities',
                    'Items of personal nature'
                ],
                'terms_conditions' => 'Booking requires 30% deposit. Full payment due 30 days before departure. Children under 5 stay free (sharing with parents). Child rates apply for ages 5-11.',
                'cancellation_policy' => 'Free cancellation up to 30 days before departure (minus 5% processing fee). 15-29 days: 50% refund. 7-14 days: 25% refund. Less than 7 days: No refund.',
                'important_notes' => 'Designed for families with children. Minimum age 3 years. Child seats available upon request. Special dietary requirements accommodated. Yellow fever vaccination required for all ages.',
                'meta_title' => '8 Days Family Safari Tanzania - Family-Friendly Wildlife Tour | Lau Paradise Adventures',
                'meta_description' => 'Family-friendly 8-day safari in Tanzania. Educational activities, shorter game drives, family accommodations, and experiences designed for children and adults.',
                'meta_keywords' => 'family safari Tanzania, family-friendly safari, safari with kids, Tanzania family tour, children safari',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            [
                'name' => '13 Days Honeymoon Safari & Zanzibar - Romantic Paradise',
                'slug' => '13-days-honeymoon-safari-zanzibar',
                'destination_id' => $serengeti->id,
                'short_description' => 'The ultimate romantic honeymoon experience combining luxury safari adventures with intimate Zanzibar beach moments, designed exclusively for couples.',
                'description' => 'Celebrate your love with this romantic 13-day honeymoon package. Experience intimate wildlife encounters, luxury accommodations, private dinners under the stars, and pristine Zanzibar beaches. Every detail is designed for romance and relaxation.',
                'long_description' => 'This is the perfect honeymoon experience for couples seeking adventure, romance, and relaxation. Begin with an intimate safari through Tanzania\'s most romantic national parks, staying in luxury tented camps with private decks and stunning views. Enjoy private game drives, romantic bush dinners, and sundowner experiences. Then, escape to Zanzibar for ultimate beachside romance with private beach villas, couples spa treatments, and intimate dining experiences. This package includes special honeymoon amenities, private transfers, and personalized service to make your honeymoon truly unforgettable.',
                'duration_days' => 13,
                'duration_nights' => 12,
                'start_location' => 'Arusha',
                'end_location' => 'Zanzibar',
                'tour_type' => 'Private',
                'max_group_size' => 2,
                'min_age' => 18,
                'price' => 4250,
                'starting_price' => 4250,
                'rating' => 5.0,
                'fitness_level' => 'low',
                'difficulty_level' => 'Easy',
                'image_url' => 'images/zanzibar_home.jpg',
                'gallery_images' => [
                    'images/hero-slider/zanzibar-beach.jpg',
                    'images/13-Days-Safari-Zanzibar-holiday-1518x1536.jpg',
                    'images/11-Days-Safari-trip-Tanzania-Zanzibar-1536x1024.jpg',
                    'images/safari_home-1.jpg',
                    'images/hero-slider/morning.jpg'
                ],
                'highlights' => [
                    'Luxury honeymoon accommodations',
                    'Private game drives for couples',
                    'Romantic bush dinners under the stars',
                    'Sundowner experiences in exclusive locations',
                    'Private beach villa in Zanzibar',
                    'Couples spa treatments',
                    'Intimate dining experiences',
                    'Honeymoon amenities and surprises',
                    'Private transfers throughout',
                    'Personalized romantic touches'
                ],
                'inclusions' => [
                    'All park entry fees and conservation fees',
                    'Private English-speaking guide',
                    'Private 4x4 vehicle (exclusive for couple)',
                    'Luxury tented camps and beach villa',
                    'All meals with romantic dining experiences',
                    'Private bush dinners and sundowners',
                    'Couples spa treatment (one per person)',
                    'Domestic flight to Zanzibar',
                    'All transfers in luxury vehicles',
                    'Premium beverages (wine, champagne)',
                    'Honeymoon amenities and special touches',
                    'Laundry service',
                    '24/7 concierge service'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance',
                    'Tips and gratuities',
                    'Additional spa treatments',
                    'Optional activities',
                    'Personal expenses',
                    'Items of personal nature'
                ],
                'terms_conditions' => 'Booking requires 50% deposit. Full payment due 45 days before departure. Honeymoon package requires proof of marriage/partnership. Premium accommodations subject to availability.',
                'cancellation_policy' => 'Free cancellation up to 45 days before departure (minus 5% processing fee). 30-44 days: 50% refund. 15-29 days: 25% refund. Less than 15 days: No refund.',
                'important_notes' => 'Designed exclusively for couples. Minimum age 18. Honeymoon amenities require advance notice. Special dietary requirements accommodated. Yellow fever vaccination required.',
                'meta_title' => '13 Days Honeymoon Safari & Zanzibar - Romantic Tanzania Honeymoon | Lau Paradise Adventures',
                'meta_description' => 'Ultimate romantic honeymoon: 13 days combining luxury safari with intimate Zanzibar beach experience. Private game drives, romantic dinners, and beachside romance.',
                'meta_keywords' => 'honeymoon safari Tanzania, romantic safari, Zanzibar honeymoon, couples safari, Tanzania honeymoon package',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            [
                'name' => 'Kilimanjaro Climbing - Lemosho Route (8 Days)',
                'slug' => 'kilimanjaro-lemosho-route-8-days',
                'destination_id' => $kilimanjaro->id,
                'short_description' => 'Conquer Kilimanjaro via the Lemosho Route, considered the most beautiful and successful route with excellent acclimatization and stunning scenery.',
                'description' => 'The Lemosho Route is widely considered Kilimanjaro\'s best route, offering excellent acclimatization, stunning scenery, and high success rates. This 8-day climb takes you through remote wilderness areas before joining the popular Machame route, providing the perfect balance of challenge and beauty.',
                'long_description' => 'The Lemosho Route is Kilimanjaro\'s premier climbing route, offering the best combination of scenery, acclimatization, and summit success rates. Starting from the western side of the mountain, this 8-day itinerary takes you through pristine rainforest, across the Shira Plateau, and up through diverse ecosystems. The extended duration allows for proper acclimatization, significantly increasing your chances of reaching Uhuru Peak. You\'ll experience remote wilderness areas, stunning sunrises, and the satisfaction of conquering Africa\'s highest peak. Our certified guides, comprehensive safety equipment, and ethical climbing practices ensure a safe and memorable experience.',
                'duration_days' => 8,
                'duration_nights' => 7,
                'start_location' => 'Moshi',
                'end_location' => 'Moshi',
                'tour_type' => 'Group',
                'max_group_size' => 10,
                'min_age' => 16,
                'price' => 3120,
                'starting_price' => 3120,
                'rating' => 4.9,
                'fitness_level' => 'very_high',
                'difficulty_level' => 'Hard',
                'image_url' => 'images/hero-slider/kilimanjaro-climbing.jpg',
                'gallery_images' => [
                    'images/hero-slider/kilimanjaro-climbing4.jpg',
                    'images/tours/kilimanjaro-featured.jpg',
                    'images/tours/kilimanjaro-marangu.jpg',
                    'images/tours/kilimanjaro-machame.jpg'
                ],
                'highlights' => [
                    'Summit Uhuru Peak (5,895m) - Africa\'s highest',
                    'Lemosho Route - highest success rate',
                    'Excellent acclimatization with 8-day itinerary',
                    'Stunning scenery through diverse ecosystems',
                    'Remote wilderness experience',
                    'Certified ethical climbing guides',
                    'Comprehensive safety equipment (oxygen, pulse oximeters)',
                    'Professional support team (guides, porters, cooks)',
                    'Summit certificate and achievement recognition',
                    'Small group size for personalized attention'
                ],
                'inclusions' => [
                    'All park fees, permits, and rescue fees',
                    'Certified mountain guide (Wilderness First Responder certified)',
                    'Assistant guides (1 guide per 2 climbers)',
                    'Porters (carry up to 20kg per person)',
                    'Professional cook and kitchen team',
                    'Camping equipment (tents, sleeping mats, mess tent)',
                    'All meals on the mountain (nutritious, high-energy)',
                    'Safety equipment (portable oxygen, pulse oximeters, first aid)',
                    'Pre-climb briefing and gear check',
                    'Airport transfers',
                    'Accommodation before and after climb (1 night each)',
                    '24/7 support from base camp'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance (mandatory)',
                    'Tips for guides and porters (recommended $250-350)',
                    'Personal climbing gear (rental available)',
                    'Additional accommodation',
                    'Alcoholic beverages',
                    'Personal expenses',
                    'Items of personal nature'
                ],
                'terms_conditions' => 'Booking requires 50% deposit. Full payment due 60 days before departure. Medical clearance required. Minimum age 16. Physical fitness assessment recommended.',
                'cancellation_policy' => 'Free cancellation up to 60 days before departure (minus 10% processing fee). 30-59 days: 50% refund. 15-29 days: 25% refund. Less than 15 days: No refund.',
                'important_notes' => 'High altitude climbing requires excellent physical fitness. Medical clearance mandatory. Altitude sickness possible. Weather conditions can affect summit attempts. Proper gear essential. Travel insurance with high-altitude coverage required.',
                'meta_title' => 'Kilimanjaro Lemosho Route 8 Days - Highest Success Rate | Lau Paradise Adventures',
                'meta_description' => 'Climb Kilimanjaro via Lemosho Route - 8 days with highest success rate. Excellent acclimatization, stunning scenery, certified guides, and comprehensive safety equipment.',
                'meta_keywords' => 'Kilimanjaro Lemosho Route, Kilimanjaro climbing, Mount Kilimanjaro, Tanzania climbing, high altitude trekking',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            [
                'name' => '7 Days Zanzibar Luxury Escape - Tropical Paradise',
                'slug' => '7-days-zanzibar-luxury-escape',
                'destination_id' => $zanzibar->id,
                'short_description' => 'Indulge in ultimate luxury on Zanzibar\'s pristine beaches. Private villas, world-class spa treatments, gourmet dining, and exclusive water activities await.',
                'description' => 'Experience Zanzibar in unparalleled luxury. This 7-day escape combines pristine beaches, private villas, world-class spa treatments, gourmet cuisine, and exclusive water activities. Perfect for relaxation, romance, or simply indulging in paradise.',
                'long_description' => 'This luxury Zanzibar escape is designed for travelers who want the ultimate beach holiday experience. Stay in private beachfront villas with personal butlers, enjoy world-class spa treatments, savor gourmet cuisine prepared by private chefs, and experience exclusive water activities. From private dhow cruises to personalized snorkeling trips, every experience is tailored to your preferences. The itinerary balances relaxation with cultural exploration, including private tours of Stone Town, spice plantation visits, and authentic Swahili dining experiences. This is the perfect escape for honeymooners, couples, or anyone seeking the ultimate tropical luxury experience.',
                'duration_days' => 7,
                'duration_nights' => 6,
                'start_location' => 'Zanzibar Airport',
                'end_location' => 'Zanzibar Airport',
                'tour_type' => 'Private',
                'max_group_size' => 4,
                'min_age' => 12,
                'price' => 1890,
                'starting_price' => 1890,
                'rating' => 5.0,
                'fitness_level' => 'low',
                'difficulty_level' => 'Easy',
                'image_url' => 'images/hero-slider/zanzibar-beach.jpg',
                'gallery_images' => [
                    'images/zanzibar_home.jpg',
                    'images/13-Days-Safari-Zanzibar-holiday-1518x1536.jpg',
                    'images/11-Days-Safari-trip-Tanzania-Zanzibar-1536x1024.jpg',
                    'images/hero-slider/morning.jpg',
                    'images/safari_home-1.jpg'
                ],
                'highlights' => [
                    'Private beachfront villa with butler service',
                    'World-class spa treatments',
                    'Gourmet cuisine with private chef',
                    'Private dhow cruises at sunset',
                    'Exclusive snorkeling and diving trips',
                    'Private Stone Town cultural tour',
                    'Spice plantation visit with cooking class',
                    'Beachside dining experiences',
                    'Water sports and activities',
                    'Personalized service throughout'
                ],
                'inclusions' => [
                    'Airport transfers in luxury vehicle',
                    'Private beachfront villa accommodation',
                    'Personal butler service',
                    'All meals (breakfast, lunch, dinner)',
                    'Premium beverages (wine, spirits, soft drinks)',
                    'Spa treatments (one per person per day)',
                    'Private dhow cruise',
                    'Snorkeling equipment and trips',
                    'Private Stone Town tour',
                    'Spice plantation visit with cooking class',
                    'Water sports equipment',
                    'Laundry service',
                    '24/7 concierge service'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance',
                    'Tips and gratuities',
                    'Scuba diving (available at extra cost)',
                    'Additional spa treatments',
                    'Personal expenses',
                    'Items of personal nature'
                ],
                'terms_conditions' => 'Booking requires 50% deposit. Full payment due 30 days before departure. Premium villa accommodation subject to availability. Single supplement applies for solo travelers.',
                'cancellation_policy' => 'Free cancellation up to 30 days before departure (minus 5% processing fee). 15-29 days: 50% refund. 7-14 days: 25% refund. Less than 7 days: No refund.',
                'important_notes' => 'Luxury accommodations require early booking. Minimum age 12. Special dietary requirements accommodated with advance notice. Yellow fever vaccination not required for Zanzibar only.',
                'meta_title' => '7 Days Zanzibar Luxury Escape - Private Villa & Spa | Lau Paradise Adventures',
                'meta_description' => 'Ultimate luxury Zanzibar escape: 7 days in private beachfront villa with butler service, spa treatments, gourmet cuisine, and exclusive water activities.',
                'meta_keywords' => 'Zanzibar luxury, private villa Zanzibar, luxury beach holiday, Zanzibar spa, tropical paradise',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
            [
                'name' => '12 Days Northern Circuit Complete Safari - Ultimate Wildlife Experience',
                'slug' => '12-days-northern-circuit-complete',
                'destination_id' => $serengeti->id,
                'short_description' => 'The most comprehensive northern circuit safari covering all major parks: Serengeti, Ngorongoro, Tarangire, Lake Manyara, and Arusha National Park for the ultimate wildlife experience.',
                'description' => 'Experience the complete northern circuit in this comprehensive 12-day safari. Visit all major national parks including Serengeti, Ngorongoro Crater, Tarangire, Lake Manyara, and Arusha National Park. This is the ultimate safari for wildlife enthusiasts who want to see it all.',
                'long_description' => 'This is the ultimate northern circuit safari experience, covering every major national park in Tanzania\'s northern circuit. Over 12 days, you\'ll explore Serengeti National Park (home to the Great Migration), descend into the Ngorongoro Crater (a natural wonder), witness massive elephant herds in Tarangire, discover the bird paradise of Lake Manyara, and explore the diverse ecosystems of Arusha National Park. With multiple nights in each park, you\'ll have ample time for game drives, wildlife photography, and truly immersing yourself in Africa\'s wilderness. This comprehensive itinerary ensures you don\'t miss any of Tanzania\'s iconic wildlife experiences.',
                'duration_days' => 12,
                'duration_nights' => 11,
                'start_location' => 'Arusha',
                'end_location' => 'Arusha',
                'tour_type' => 'Private',
                'max_group_size' => 6,
                'min_age' => 8,
                'price' => 3450,
                'starting_price' => 3450,
                'rating' => 4.9,
                'fitness_level' => 'moderate',
                'difficulty_level' => 'Medium',
                'image_url' => 'images/10-Days-Tanzania-safari-all-northern-parks-in-1-trip-wildebeest-migration-1536x1026.webp',
                'gallery_images' => [
                    'images/Serengetei-NP-2.jpeg',
                    'images/Tarangire-NP-1.jpeg',
                    'images/Mara-River-3-1536x1024.jpg',
                    'images/safari_home-1.jpg'
                ],
                'highlights' => [
                    'Complete northern circuit coverage',
                    'Serengeti National Park (multiple nights)',
                    'Ngorongoro Crater descent',
                    'Tarangire elephant herds',
                    'Lake Manyara bird watching',
                    'Arusha National Park exploration',
                    'Great Migration viewing opportunities',
                    'Big Five viewing',
                    'Multiple game drives in each park',
                    'Expert guides with extensive knowledge'
                ],
                'inclusions' => [
                    'All park entry fees and conservation fees',
                    'Professional English-speaking guide',
                    'Private 4x4 safari vehicle with pop-up roof',
                    'Luxury tented camp and lodge accommodation',
                    'All meals (breakfast, lunch, dinner)',
                    'Multiple game drives in each park',
                    'Ngorongoro Crater descent',
                    'Airport transfers',
                    'Unlimited drinking water and soft drinks',
                    'Binoculars and field guides',
                    '24/7 support from local team'
                ],
                'exclusions' => [
                    'International flights',
                    'Visa fees',
                    'Travel insurance',
                    'Tips and gratuities',
                    'Alcoholic beverages',
                    'Personal expenses',
                    'Optional activities (hot air balloon, etc.)',
                    'Items of personal nature'
                ],
                'terms_conditions' => 'Booking requires 30% deposit. Full payment due 30 days before departure. Comprehensive itinerary subject to weather and wildlife movements.',
                'cancellation_policy' => 'Free cancellation up to 30 days before departure (minus 5% processing fee). 15-29 days: 50% refund. 7-14 days: 25% refund. Less than 7 days: No refund.',
                'important_notes' => 'Comprehensive safari covering multiple parks. Minimum age 8 years. Yellow fever vaccination required. Malaria prophylaxis recommended. Weather-dependent activities may be modified.',
                'meta_title' => '12 Days Northern Circuit Complete Safari - All Major Parks | Lau Paradise Adventures',
                'meta_description' => 'Complete northern circuit safari: 12 days covering Serengeti, Ngorongoro, Tarangire, Lake Manyara, and Arusha National Parks. Ultimate wildlife experience.',
                'meta_keywords' => 'northern circuit safari, complete Tanzania safari, Serengeti, Ngorongoro, Tarangire, Lake Manyara, Arusha National Park',
                'availability_status' => 'Available',
                'is_featured' => true,
                'status' => 'active',
                'publish_status' => 'published'
            ],
        ];

        foreach ($tours as $tourData) {
            Tour::updateOrCreate(
                ['slug' => $tourData['slug']],
                $tourData
            );
        }

        $this->command->info('Successfully seeded ' . count($tours) . ' tours from Tanzania Specialist content!');
    }
}





