@php
use App\Models\OrganizationSetting;

$orgSettings = OrganizationSetting::getSettings();
$systemName = config('app.name', 'Lau Paradise Adventures');

if ($systemName === 'Laravel' || empty($systemName)) {
    $systemName = 'Lau Paradise Adventures';
}

// Ensure timezone is a string, not an array
$timezone = $orgSettings->timezone ?? config('app.timezone', 'Africa/Dar_es_Salaam');
if (is_array($timezone)) {
    $timezone = config('app.timezone', 'Africa/Dar_es_Salaam');
    \Log::warning('Timezone is an array in pdf-disclaimer', ['timezone' => $timezone]);
} else {
    $timezone = (string)$timezone;
}

$generatedAtFull = now()->setTimezone($timezone)->format('d M Y, H:i:s') . ' (' . $timezone . ')';
@endphp

<div style="margin-top: 30px; padding-top: 15px; font-size: 9px; color: #666; text-align: center; page-break-inside: avoid;">
    <p style="margin: 0; font-style: italic;">This document was automatically generated by {{ $systemName }} System on {{ $generatedAtFull }}. No manual signature is required.</p>
</div>


