<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset - {{ config('app.name', 'TourPilot') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f4f4f4;
        }
        .email-container {
            background-color: white;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            background: linear-gradient(135deg, #1a4d3e 0%, #2d7a5f 100%);
            color: white;
            padding: 30px 20px;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .content {
            padding: 30px;
        }
        .password-box {
            background-color: #f8f9fa;
            border: 2px dashed #1a4d3e;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            margin: 20px 0;
        }
        .password-box .password {
            font-size: 24px;
            font-weight: bold;
            color: #1a4d3e;
            letter-spacing: 2px;
            font-family: 'Courier New', monospace;
            padding: 10px;
            background-color: white;
            border-radius: 4px;
            margin: 10px 0;
        }
        .warning-box {
            background-color: #fff3cd;
            color: #856404;
            padding: 15px;
            border-radius: 5px;
            border-left: 4px solid #ffc107;
            margin: 20px 0;
        }
        .info-box {
            background-color: #e7f3ff;
            color: #004085;
            padding: 15px;
            border-radius: 5px;
            border-left: 4px solid #2196F3;
            margin: 20px 0;
        }
        .footer {
            background-color: #f8f9fa;
            padding: 20px;
            text-align: center;
            color: #6c757d;
            font-size: 12px;
            border-top: 1px solid #dee2e6;
        }
        .cta-button {
            display: inline-block;
            background-color: #1a4d3e;
            color: white;
            padding: 12px 30px;
            text-decoration: none;
            border-radius: 5px;
            margin: 20px 0;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="header">
            <h1>{{ config('app.name', 'TourPilot') }}</h1>
            <p style="margin: 10px 0 0 0; opacity: 0.9;">Password Reset Notification</p>
        </div>
        
        <div class="content">
            <p>Dear {{ $user->name }},</p>
            
            <p>Your password has been reset by an administrator. Please find your new temporary password below:</p>
            
            <div class="password-box">
                <p style="margin: 0 0 10px 0; font-weight: bold; color: #495057;">Your New Password:</p>
                <div class="password">{{ $newPassword }}</div>
                <p style="margin: 10px 0 0 0; font-size: 12px; color: #6c757d;">Please copy this password and keep it secure</p>
            </div>
            
            <div class="warning-box">
                <strong>⚠️ Important Security Notice:</strong>
                <ul style="margin: 10px 0 0 20px; padding: 0;">
                    <li>This is a temporary password generated by the system</li>
                    <li>Please change your password immediately after logging in</li>
                    <li>Do not share this password with anyone</li>
                    <li>If you did not request this password reset, please contact support immediately</li>
                </ul>
            </div>
            
            <div class="info-box">
                <strong>📋 Next Steps:</strong>
                <ol style="margin: 10px 0 0 20px; padding: 0;">
                    <li>Log in to your account using the new password above</li>
                    <li>Go to your account settings</li>
                    <li>Change your password to something memorable and secure</li>
                </ol>
            </div>
            
            <div style="text-align: center; margin: 30px 0;">
                <a href="{{ route('login') }}" class="cta-button">Login to Your Account</a>
            </div>
            
            <p>If you have any questions or concerns, please don't hesitate to contact our support team.</p>
        </div>
        
        <div class="footer">
            <p><strong>{{ config('app.name', 'TourPilot') }}</strong></p>
            <p>Tanzania's premier tour operator</p>
            <p style="margin-top: 15px;">
                <a href="mailto:lauparadiseadventure@gmail.com" style="color: #1a4d3e;">lauparadiseadventure@gmail.com</a> | 
                <a href="tel:+255683163219" style="color: #1a4d3e;">+255 683 163 219</a>
            </p>
            <p style="margin-top: 10px; font-size: 11px; color: #999;">
                This is an automated email. Please do not reply directly to this message.
            </p>
        </div>
    </div>
</body>
</html>






